export default {
  INCREMENT_ACTION: 'COUNTER_PLUS',
  DECREMENT_ACTION: 'COUNTER_MINUS',
  CHANGE_STEP: 'CHANGE_STEP',
  REQUEST_COUNTER_FETCHING: 'REQUEST_COUNTER_FETCHING',
  REQUEST_COUNTER_SUCCESS: 'REQUEST_COUNTER_SUCCESS',
  REQUEST_COUNTER_ERROR: 'REQUEST_COUNTER_ERROR',
  CLICKER_FETCH: 'CLICKER_FETCH',
  CLICKER_RESPONSE_SUCCESS: 'CLICKER_RESPONSE_SUCCESS',
  CLICKER_RESPONSE_ERROR: 'CLICKER_RESPONSE_ERROR'
};
